server:
  port: 8082

spring:
  application:
    name: category-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/category_db}
    username: ${SPRING_DATASOURCE_USERNAME:category}
    password: ${SPRING_DATASOURCE_PASSWORD:category}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

cache:
  type: redis

logging:
  level:
    com.example.category: INFO
